apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ec2-cluster
spec:
  destination:
    name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'capi-cluster/aws-ec2'
    repoURL: 'https://github.com/Tungdever/multi-cluster-with-clusterapi'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      allowEmpty: true
